name: Checkmarx SAST Scan
 
on:
  push:
    branches:
      - master
jobs:
  checkmarx-cli-san:
    name: Run Checkmarx CLI Scan
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, windows, x64]
    #runs-on: [self-hosted, linux, x64]
    steps:
    
    - name: Download CxCLI Zip
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
        Invoke-WebRequest -Uri https://download.checkmarx.com/9.0.0/Plugins/CxConsolePlugin-2020.4.4.zip -OutFile cxcli.zip
    - name: Unzip CxCLI Zip
      run: Expand-Archive -Path .\cxcli.zip -DestinationPath .\cxcli
           
    - uses: actions/checkout@v1
    - name: Run Checkmarx Scan
      env:
        CX_PROJECT_NAME: $("$GITHUB_REPOSITORY")
        BRANCH: $("$GITHUB_REF")
        CX_SERVER: "https://cxprivatecloud.checkmarx.net/"
        CX_TEAM: ${{ secrets.CX_TEAM }}
        CX_PRESET: "Checkmarx Default"
        CX_USER: ${{ secrets.CX_USER }}
        CX_PASSWORD: ${{ secrets.CX_PASSWORD }}
        CX_HIGH: 1000
        CX_MEDIUM: 1000
        CX_LOW: 1000
      run: runCxConsole.cmd Scan -CxServer "${CX_SERVER}" -CxUser "${{ secrets.CX_USER }}" -CxPassword "${{ secrets.CX_PASSWORD }}" -ProjectName "${CX_TEAM}\\${CX_PROJECT_NAME}-${BRANCH}" -preset "${CX_PRESET}" -LocationType folder -LocationPath "$GITHUB_WORKSPACE" -SASTHigh ${CX_HIGH} -SASTMedium ${CX_MEDIUM} -SASTLow ${CX_LOW} -ReportXML ${GITHUB_WORKSPACE}/results.xml -ReportPDF ${GITHUB_WORKSPACE}/results.pdf -Comment "git ${BRANCH}@$GITHUB_SHA" -verbose
        
    - name: Upload PDF Artifact
      uses: actions/upload-artifact@master
      with:
        name: results.pdf
        path: results.pdf
    - name: Upload XML Artifact
      uses: actions/upload-artifact@master
      with:
        name: results.xml
        path: results.xml
